# Generated by Django 5.2.14 on 2026-05-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_security_fields_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_user_id_d4cccd_idx',
            old_name='accounts_au_user_id_0a1b2c_idx',
        ),
    ]
