# Generated by Django 5.2.15 on 2026-06-16 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_enabled', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('notify_new_workflow', models.BooleanField(default=True)),
                ('notify_new_task', models.BooleanField(default=True)),
                ('notify_new_goal', models.BooleanField(default=True)),
                ('notify_feedback', models.BooleanField(default=True)),
                ('notify_deadline_reminder', models.BooleanField(default=True)),
                ('notify_group_chat_mentions', models.BooleanField(default=True)),
                ('notify_group_chat_all_messages', models.BooleanField(default=False)),
                ('digest_mode', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='instant', max_length=16)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/Zurich', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification settings',
                'verbose_name_plural': 'notification settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('slack', 'Slack')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='accounts_no_recipie_2ecacc_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_key', 'recipient', 'channel'), name='accounts_deliverylog_event_recipient_channel_uniq')],
            },
        ),
    ]
