# Generated by Django 5.2.15 on 2026-06-16
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_channel_notification_prefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack')], max_length=16)),
                ('digest_bucket', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], max_length=16)),
                ('event_key', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_body', models.TextField(blank=True)),
                ('slack_text', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('scheduled_for', models.DateTimeField()),
                (
                    'status',
                    models.CharField(
                        choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')],
                        default='queued',
                        max_length=16,
                    ),
                ),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                (
                    'recipient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notification_digest_items',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['recipient', 'digest_bucket', 'scheduled_for', 'status'],
                        name='digitem_recipient_bucket_idx',
                    ),
                    models.Index(
                        fields=['channel', 'digest_bucket', 'scheduled_for', 'status'],
                        name='digitem_channel_bucket_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=['event_key', 'recipient', 'channel', 'digest_bucket'],
                        name='accounts_digestitem_event_recipient_channel_bucket_uniq',
                    ),
                ],
            },
        ),
    ]

