# Generated by Django 5.2.15 on 2026-06-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resourcecontainer_project_space_and_more'),
        ('workflows', '0002_alter_workflow_description_alter_workflow_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='resource_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='resources.resourcecontainer'),
        ),
    ]
