# Generated by Django 5.2.15 on 2026-06-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_resource_container_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='scheduled_publish_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
