# Generated by Django 5.2.14 on 2026-05-31 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('entry_date', models.DateField()),
                ('mood', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('struggling', 'Struggling'), ('tough', 'Tough')], max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Only me'), ('shared', 'Visible to teachers')], default='private', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['author', '-entry_date'], name='journal_jou_author__8852b4_idx'), models.Index(fields=['author', 'visibility'], name='journal_jou_author__e49fd7_idx'), models.Index(fields=['title'], name='journal_jou_title_b07635_idx')],
            },
        ),
    ]
