# Generated by Django 5.2.14 on 2026-05-30 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee_cohort',
            field=models.ForeignKey(blank=True, help_text='Set when staff assigns via cohort picker (individual progress per student).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort_tasks', to='cohorts.cohort'),
        ),
    ]
