# Generated by Django 5.2.14 on 2026-06-05 05:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def forwards_subtask_enrollments(apps, schema_editor):
    SubtaskCompletion = apps.get_model('tasks', 'SubtaskCompletion')
    SubtaskEnrollment = apps.get_model('tasks', 'SubtaskEnrollment')
    TaskEnrollment = apps.get_model('tasks', 'TaskEnrollment')
    Subtask = apps.get_model('tasks', 'Subtask')

    for completion in SubtaskCompletion.objects.all():
        SubtaskEnrollment.objects.update_or_create(
            enrollment_id=completion.enrollment_id,
            subtask_id=completion.subtask_id,
            defaults={
                'status': 'done',
                'completed_at': completion.completed_at,
            },
        )

    for enrollment in TaskEnrollment.objects.all():
        for subtask in Subtask.objects.filter(task_id=enrollment.task_id):
            if subtask.added_by_id and subtask.added_by_id != enrollment.student_id:
                continue
            SubtaskEnrollment.objects.get_or_create(
                enrollment_id=enrollment.pk,
                subtask_id=subtask.pk,
                defaults={'status': 'todo'},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_subtask_title_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='SubtaskEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'To do'), ('doing', 'Doing'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_enrollments', to='tasks.taskenrollment')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tasks.subtask')),
            ],
            options={
                'ordering': ['subtask__order', 'subtask__pk'],
            },
        ),
        migrations.RunPython(forwards_subtask_enrollments, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SubtaskCompletion',
        ),
        migrations.AddConstraint(
            model_name='subtaskenrollment',
            constraint=models.UniqueConstraint(fields=('enrollment', 'subtask'), name='unique_subtask_enrollment'),
        ),
    ]
