# Generated by Django 5.2.15 on 2026-06-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_storage', '0002_alter_googleaccountconnection_refresh_token_encrypted'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driveuploadlog',
            new_name='google_stor_status_450919_idx',
            old_name='google_stor_status_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='googleaccountconnection',
            new_name='google_stor_google__5785ef_idx',
            old_name='google_stor_google__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='googledrivefolder',
            new_name='google_stor_storage_5524f9_idx',
            old_name='google_stor_storage_4d5e6f_idx',
        ),
    ]
