# Generated by Django 5.2.14 on 2026-05-25 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0002_simplify_goal_and_reflection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('did_today', models.TextField()),
                ('progress_made', models.TextField()),
                ('blockers', models.TextField(blank=True)),
                ('next_steps', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'daily journal entry',
                'verbose_name_plural': 'daily journal entries',
                'ordering': ['-entry_date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'entry_date'), name='unique_journal_entry_per_student_per_day')],
            },
        ),
    ]
