# Generated by Django 5.2.14 on 2026-05-25 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0005_add_habit_and_habitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='target_days_per_week',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='habit',
            name='times_per_day',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
