# Generated by Django 5.2.14 on 2026-05-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0006_habit_target_days_per_week_habit_times_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='times_per_day',
        ),
    ]
