# Generated by Django 5.2.14 on 2026-05-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0007_remove_habit_times_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed_weekly_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
