# Generated by Django 5.2.14 on 2026-05-26 08:46

from django.db import migrations


def convert_stress_to_calmness(apps, schema_editor):
    """Invert existing stress values: calmness = 11 - stress."""
    WellbeingCheckIn = apps.get_model('growth', 'WellbeingCheckIn')
    for checkin in WellbeingCheckIn.objects.all():
        checkin.calmness = 11 - checkin.calmness
        checkin.save(update_fields=['calmness'])


def convert_calmness_to_stress(apps, schema_editor):
    """Reverse: stress = 11 - calmness."""
    WellbeingCheckIn = apps.get_model('growth', 'WellbeingCheckIn')
    for checkin in WellbeingCheckIn.objects.all():
        checkin.calmness = 11 - checkin.calmness
        checkin.save(update_fields=['calmness'])


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0009_wellbeingcheckin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellbeingcheckin',
            old_name='stress',
            new_name='calmness',
        ),
        migrations.RunPython(
            convert_stress_to_calmness,
            convert_calmness_to_stress,
        ),
    ]
