# Generated by Django 5.2.14 on 2026-05-26 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_created_by_to_student(apps, schema_editor):
    """For existing goals, set created_by = student (self-created)."""
    Goal = apps.get_model('growth', 'Goal')
    for goal in Goal.objects.filter(created_by__isnull=True):
        goal.created_by = goal.student
        goal.save(update_fields=['created_by'])


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0010_rename_stress_to_calmness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            set_created_by_to_student,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='GoalSubgoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgoals_created', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='growth.goal')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
