# Generated by Django 5.2.14 on 2026-05-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='achieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
