# Generated by Django 5.2.14 on 2026-05-30 06:07

import django.db.models.deletion
from collections import defaultdict

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def migrate_goals_to_enrollments(apps, schema_editor):
    Goal = apps.get_model('goals', 'Goal')
    Milestone = apps.get_model('goals', 'Milestone')
    GoalEnrollment = apps.get_model('goals', 'GoalEnrollment')
    MilestoneCompletion = apps.get_model('goals', 'MilestoneCompletion')

    for goal in Goal.objects.all().iterator():
        GoalEnrollment.objects.get_or_create(
            goal_id=goal.pk,
            student_id=goal.author_id,
            defaults={
                'status': goal.status,
                'achieved_at': goal.achieved_at,
            },
        )

    for goal in Goal.objects.all().iterator():
        enrollment = GoalEnrollment.objects.get(goal_id=goal.pk, student_id=goal.author_id)
        for ms in Milestone.objects.filter(goal_id=goal.pk).order_by('order', 'pk'):
            if ms.completed:
                MilestoneCompletion.objects.get_or_create(
                    enrollment_id=enrollment.pk,
                    milestone_id=ms.pk,
                )

    staff_goals = (
        Goal.objects.filter(created_by_id__isnull=False)
        .exclude(created_by_id=F('author_id'))
        .order_by('pk')
    )

    groups = defaultdict(list)
    for goal in staff_goals:
        key = (
            goal.created_by_id,
            goal.title,
            goal.description or '',
            goal.category,
            goal.visibility,
            goal.target_date,
            goal.created_at.replace(second=0, microsecond=0) if goal.created_at else None,
        )
        groups[key].append(goal)

    for goals in groups.values():
        if len(goals) == 1:
            goal = goals[0]
            goal.author_id = None
            goal.save(update_fields=['author_id'])
            continue

        template = goals[0]
        template_ms = list(Milestone.objects.filter(goal=template).order_by('order', 'pk'))
        template.author_id = None
        template.save(update_fields=['author_id'])

        for duplicate in goals[1:]:
            dup_ms = list(Milestone.objects.filter(goal=duplicate).order_by('order', 'pk'))
            enrollment = GoalEnrollment.objects.get(goal=duplicate)
            enrollment.goal_id = template.pk
            enrollment.save(update_fields=['goal_id'])

            for comp in MilestoneCompletion.objects.filter(enrollment=enrollment):
                old_ms = comp.milestone
                idx = next((i for i, m in enumerate(dup_ms) if m.pk == old_ms.pk), None)
                if idx is not None and idx < len(template_ms):
                    comp.milestone_id = template_ms[idx].pk
                    comp.save(update_fields=['milestone_id'])

            duplicate.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_achieved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='goals.goal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__display_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_completions', to='goals.goalenrollment')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='goals.milestone')),
            ],
            options={
                'ordering': ['completed_at'],
            },
        ),
        migrations.AlterField(
            model_name='goal',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Set for student-created goals; null for staff-assigned templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='goalenrollment',
            index=models.Index(fields=['student', 'status'], name='goals_goale_student_d1610a_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalenrollment',
            constraint=models.UniqueConstraint(fields=('goal', 'student'), name='unique_goal_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='milestonecompletion',
            constraint=models.UniqueConstraint(fields=('enrollment', 'milestone'), name='unique_milestone_completion'),
        ),
        migrations.RunPython(migrate_goals_to_enrollments, noop),
    ]
