# Generated by Django 5.2.15 on 2026-06-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_goal_description_alter_goal_title_and_more'),
        ('resources', '0004_resourcecontainer_project_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='resource_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='resources.resourcecontainer'),
        ),
    ]
