# Generated by Django 5.2.14 on 2026-05-31 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        ('group_space', '0003_chat_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(choices=[('personal', 'Personal'), ('group', 'Group'), ('thematic', 'Thematic')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('is_system', models.BooleanField(default=False, help_text='Auto-created group container synced from Group chat (one per cohort group).')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resource_containers', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_containers', to='cohorts.group')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_resource_containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=2048)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.resourcecontainer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_items', to=settings.AUTH_USER_MODEL)),
                ('source_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_item', to='group_space.post')),
            ],
            options={
                'ordering': ['sort_order', 'title', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='resourcecontainer',
            index=models.Index(fields=['container_type', 'owner'], name='resources_r_contain_7b99bc_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecontainer',
            index=models.Index(fields=['container_type', 'group'], name='resources_r_contain_25677f_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcecontainer',
            constraint=models.UniqueConstraint(condition=models.Q(('container_type', 'group'), ('is_system', True)), fields=('group',), name='resources_one_system_container_per_group'),
        ),
        migrations.AddIndex(
            model_name='resourceitem',
            index=models.Index(fields=['container', 'sort_order'], name='resources_r_contain_d4223d_idx'),
        ),
    ]
