# Generated by Django 5.2.15 on 2026-06-17 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
        ('group_space', '0006_projectspacemembership_alter_post_group_space_and_more'),
        ('resources', '0003_resourceitem_drive_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecontainer',
            name='project_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_containers', to='group_space.projectspace'),
        ),
        migrations.AlterField(
            model_name='resourcecontainer',
            name='container_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group'), ('project', 'Project'), ('thematic', 'Thematic')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='resourcecontainer',
            index=models.Index(fields=['container_type', 'project_space'], name='resources_r_contain_e6b73b_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcecontainer',
            constraint=models.UniqueConstraint(condition=models.Q(('container_type', 'project'), ('is_system', True)), fields=('project_space',), name='resources_one_system_container_per_project'),
        ),
    ]
