# Generated by Django 5.2.14 on 2026-05-19 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_upcoming_to_planned(apps, schema_editor):
    Cohort = apps.get_model("cohorts", "Cohort")
    Cohort.objects.filter(status="upcoming").update(status="planned")


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['-start_date', 'name']},
        ),
        migrations.AddField(
            model_name='cohort',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohort',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_upcoming_to_planned, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cohorts.cohort')),
            ],
            options={
                'ordering': ['cohort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('teacher', 'Teacher'), ('assistant', 'Assistant'), ('observer', 'Observer')], default='teacher', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teachers', to='cohorts.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teacher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'teacher'],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('cohort', 'name'), name='unique_group_name_per_cohort'),
        ),
        migrations.AddConstraint(
            model_name='groupteacher',
            constraint=models.UniqueConstraint(fields=('group', 'teacher'), name='unique_teacher_per_group'),
        ),
    ]
