# Generated by Django 5.2.14 on 2026-05-31 19:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_space', to='cohorts.group')),
            ],
            options={
                'ordering': ['group__cohort__name', 'group__name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('file', models.FileField(blank=True, null=True, upload_to='group_files/%Y/%m/')),
                ('resource_label', models.CharField(blank=True, help_text='Required when the post includes a file or URL — title on Resources tiles.', max_length=100)),
                ('pinned', models.BooleanField(default=False)),
                ('snapshot_kind', models.CharField(blank=True, choices=[('journal', 'Journal entry'), ('habit', 'Habit'), ('goal', 'Goal'), ('task', 'Task')], max_length=20)),
                ('snapshot_html', models.TextField(blank=True)),
                ('snapshot_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL)),
                ('group_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='group_space.groupspace')),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='group_space.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group_space', 'pinned', 'created_at'], name='group_space_group_s_3e5298_idx'),
        ),
    ]
