# Generated by Django 5.2.14 on 2026-05-31 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_space', '0002_backfill_group_spaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='group_space_group_s_3e5298_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group_space', 'created_at'], name='group_space_group_s_48b0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group_space', 'pinned'], name='group_space_group_s_ffa551_idx'),
        ),
    ]
