# Generated by Django 5.2.15 on 2026-06-17 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_space', '0005_post_drive_doc_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSpaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='group_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='group_space.groupspace'),
        ),
        migrations.CreateModel(
            name='ProjectSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_project_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='project_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='group_space.projectspace'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['project_space', 'created_at'], name='group_space_project_dcec55_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['project_space', 'pinned'], name='group_space_project_5dbce4_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group_space__isnull', False), ('project_space__isnull', True)), models.Q(('group_space__isnull', True), ('project_space__isnull', False)), _connector='OR'), name='group_space_post_exactly_one_parent'),
        ),
        migrations.AddField(
            model_name='projectspacemembership',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_memberships_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectspacemembership',
            name='project_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='group_space.projectspace'),
        ),
        migrations.AddField(
            model_name='projectspacemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_space_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectspace',
            index=models.Index(fields=['is_archived', 'title'], name='group_space_is_arch_407747_idx'),
        ),
        migrations.AddIndex(
            model_name='projectspace',
            index=models.Index(fields=['created_by'], name='group_space_created_b3a989_idx'),
        ),
        migrations.AddIndex(
            model_name='projectspacemembership',
            index=models.Index(fields=['project_space', 'role'], name='group_space_project_e7872a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectspacemembership',
            index=models.Index(fields=['user'], name='group_space_user_id_33ba82_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectspacemembership',
            constraint=models.UniqueConstraint(fields=('project_space', 'user'), name='group_space_unique_project_member'),
        ),
    ]
