from config.input_limits import DESCRIPTION_MAX_LENGTH, TITLE_MAX_LENGTH

TITLE_MAX = TITLE_MAX_LENGTH
DESCRIPTION_MAX = DESCRIPTION_MAX_LENGTH

MINUTES_MIN = 1
DAYS_PER_WEEK_MIN = 1
DAYS_PER_WEEK_MAX = 7
DAYS_PER_WEEK_DEFAULT = 7
