# Generated by Django 5.2.14 on 2026-05-31 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_label', models.CharField(blank=True, max_length=100)),
                ('expectations', models.TextField(blank=True)),
                ('final_reflection', models.TextField(blank=True)),
                ('energy', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('struggling', 'Struggling'), ('tough', 'Tough')], max_length=20)),
                ('calmness', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('struggling', 'Struggling'), ('tough', 'Tough')], max_length=20)),
                ('engagement', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('struggling', 'Struggling'), ('tough', 'Tough')], max_length=20)),
                ('concentration', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('struggling', 'Struggling'), ('tough', 'Tough')], max_length=20)),
                ('sleep', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('struggling', 'Struggling'), ('tough', 'Tough')], max_length=20)),
                ('physical_activity', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('struggling', 'Struggling'), ('tough', 'Tough')], max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Only me'), ('shared', 'Visible to teachers')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['author', 'visibility'], name='reflections_author__0bbabc_idx'), models.Index(fields=['title'], name='reflections_title_4b58fb_idx')],
            },
        ),
    ]
