# Generated by Django 5.2.14 on 2026-05-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='final_reflection_at',
            field=models.DateTimeField(blank=True, help_text='Set when the student saves a non-empty final reflection.', null=True),
        ),
    ]
