# Generated by Django 5.2.14 on 2026-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0002_add_final_reflection_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='expectations_at',
            field=models.DateTimeField(blank=True, help_text='Last save when expectations contain real content.', null=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='final_reflection_at',
            field=models.DateTimeField(blank=True, help_text='Last save when final reflection contains real content.', null=True),
        ),
    ]
