# Generated by Django 5.2.14 on 2026-05-31 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0004_field_length_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='custom_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='expectations',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='final_reflection',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
