# Generated by Django 5.2.14 on 2026-05-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedbackentry',
            new_name='feedback_fe_content_364176_idx',
            old_name='feedback_fe_content_0a1b2c_idx',
        ),
    ]
