# Generated by Django 5.2.14 on 2026-05-31 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_feedback_fe_content_0a1b2c_idx_feedback_fe_content_364176_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackentry',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
